/// Physiological activation ("arousal") weight per emotion, on a -5..+5
/// scale — the Y axis of the energy quadrant (Экран 1). Independent of
/// valence (that's the X axis, computed from `emotionInDayEvent` +
/// `emotionIntensity`): this table only encodes how activating/calming the
/// emotion itself tends to be, per Russell's circumplex model. Calibrated
/// together with the product owner; paired neutral emotions
/// (`_positive`/`_negative`, `_+`/`_-`) intentionally share one weight since
/// activation doesn't depend on the pair's valence side.
class EnergyWeights {
  static const Map<String, int> byEmotionKey = {
    // standardEventListOne — negative emotions
    'anger_rage': 5,
    'hate': 4,
    'wrath': 5,
    'irritation': 2,
    'contempt': 0,
    'outrage2': 4,
    'resentment': 1,
    'jealousy': 4,
    'vulnerability': 1,
    'annoyance': 2,
    'envy': 2,
    'antipathy': 0,
    'outrage': 4,
    'disgust': 2,
    'fear2': 4,
    'horror': 5,
    'desperation': 3,
    'fear': 4,
    'suspicion': 2,
    'anxiety': 4,
    'worry': 3,
    'bitterness': -1,
    'humiliation': 2,
    'sadness': -3,
    'guilt': 1,
    'shame2': -2,
    'shyness': -1,
    'apprehension': 2,
    'sorrow': -3,
    'melancholy': -3,
    'grief': -4,
    'laziness': -3,
    'pity': -1,
    'agitation': 5,
    'helplessness': -4,
    'disappointment': -2,
    'regret2': -2,
    'uncertainty': 0,
    'apathy': -5,
    'loneliness': -3,
    'abandonment': -3,
    'lostness': -3,
    'desolation': -4,
    'busyness': 2,
    'powerlessness': -4,
    'confusion2': 0,
    'melancholia': -4,
    'unworthiness': -3,
    'doom': 3,
    'detachment': -4,
    'prostration': -5,
    'cruelty': 0,
    'disgust_disappointment': -1,
    'confusion': 0,
    'disheartenment': -3,
    'regret': -2,
    'bewilderment2': 0,
    'distrust': 1,
    'shame': -2,
    'repulsion': 2,
    'bewilderment': 0,

    // standardEventListTwo — positive emotions
    'joy': 4,
    'happiness': 2,
    'delight': 3,
    'joy2': 4,
    'elevation': 3,
    'animation': 4,
    'pacification': -3,
    'interest': 2,
    'care': 0,
    'anticipation': 3,
    'excitement': 5,
    'anticipation2': 3,
    'hope': 1,
    'gratitude': -1,
    'liberation': 3,
    'acceptance': -2,
    'acceptance2': -2,
    'faith': -1,
    'love': -1,
    'reliability': -2,
    'trust': -2,
    'tranquility': -5,
    'sympathy': -1,
    'identity': 0,
    'pride': 2,
    'admiration': 1,
    'respect': -1,
    'self-worth': -1,
    'infatuation': 4,
    'self-love': -2,
    'enchantment': 2,
    'humility': -3,
    'friendliness': 0,
    'kindness': -1,
    'harmony': -3,
    'bliss': -2,
    'euphoria': 5,
    'inspiration': 3,
    'vitality': 4,
    'pleasure': 1,
    'inspiration2': 3,
    'enthusiasm': 5,
    'zeal': 5,
    'tenderness': -3,
    'reverence': -2,
    'gratitude2': -1,
    'patriotism': 2,

    // standardEventListThree — neutral/ambivalent pairs (same weight both sides)
    'doubt_positive': 1,
    'doubt_negative': 1,
    'surprise_positive': 4,
    'surprise_negative': 4,
    'indifference_positive': -4,
    'indifference_negative': -4,
    'excitement_positive': 5,
    'excitement_negative': 5,
    'euphoria_positive': 5,
    'euphoria_negative': 5,
    'excitement_over': 3,
    'excitement_down': 3,
    'nervousness_positive': 3,
    'nervousness_negative': 3,
    'excitement_up': 4,
    'excitement_down2': 4,
    'impatience_positive': 2,
    'impatience_negative': 2,
    'nostalgia_positive': -2,
    'nostalgia_negative': -2,
    'curiosity_+': 1,
    'curiosity_-': 1,
    'embarrassment_+': 2,
    'embarrassment_-': 2,
    'adoration_+': -1,
    'adoration_-': -1,
    'compassion_+': -1,
    'compassion_-': -1,
    'empathy_+': -1,
    'empathy_-': -1,
    'sympathy_+': -1,
    'sympathy_-': -1,
  };

  /// Falls back to 0 (neutral activation) for anything not in the table —
  /// in practice only reachable for a custom user-typed emotion, since the
  /// seeded lists above are exhaustive for the app's own taxonomy.
  static int weightFor(String emotionKey) => byEmotionKey[emotionKey] ?? 0;
}
